name: Merge bump branch

on:
  push:
    branches:
      - bump/beta/*
      - bump/rc/*

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approved!"

  merge-bump:
    runs-on: ubuntu-latest
    needs: [approved]
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: npm run release merge-bump
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
