name: Pull requests

on:
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      branch: ${{ github.base_ref }}

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      branch: ${{ github.base_ref }}

  upload:
    needs: [validate]
    uses: ./.github/workflows/upload.yml

  integration-tests:
    needs: [upload]
    uses: ./.github/workflows/integration-tests.yml

  e2e-tests:
    needs: [upload]
    uses: ./.github/workflows/e2e-tests.yml

  github-actions-tests:
    needs: [upload]
    uses: ./.github/workflows/github-actions-tests.yml

  approved:
    needs: [integration-tests, e2e-tests, github-actions-tests]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ needs.integration-tests.result }}" == "success" && "${{ needs.e2e-tests.result }}" == "success" ]]; then
            echo "Approved!"
          else
            echo "Not approved!"
            exit 1
          fi
