name: Pull requests

on:
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      branch: ${{ github.base_ref }}

  upload:
    needs: [validate]
    uses: ./.github/workflows/upload.yml

  integration-tests:
    needs: [upload]
    uses: ./.github/workflows/integration-tests.yml

  cicd-tests:
    needs: [upload]
    uses: ./.github/workflows/cicd-tests.yml

  approved:
    needs: [integration-tests, cicd-tests]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.integration-tests.result == 'success' }}
        run: echo "Approved!"
      - if: ${{ needs.integration-tests.result != 'success' }}
        run: echo "Not approved!" && exit 1
