name: Push branch

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      branch: ${{ github.ref_name }}

  upload:
    needs: [validate]
    uses: ./.github/workflows/upload.yml

  integration-tests:
    needs: [upload]
    uses: ./.github/workflows/integration-tests.yml

  e2e-tests:
    needs: [upload]
    uses: ./.github/workflows/e2e-tests.yml
    secrets:
      AUTIFY_CLI_E2E_AUTIFY_MOBILE_ACCESS_TOKEN: ${{ secrets.AUTIFY_CLI_E2E_AUTIFY_MOBILE_ACCESS_TOKEN }}

  github-actions-tests:
    needs: [upload]
    uses: ./.github/workflows/github-actions-tests.yml

  promote:
    needs: [integration-tests, e2e-tests, github-actions-tests]
    uses: ./.github/workflows/promote.yml
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
