name: Rollback

on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          aws-credentials: releases/*
      - run: npm install
      - run: npm run release rollback
