name: Upload

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  tarball:
    strategy:
      matrix:
        target:
          [
            "darwin-arm64",
            "darwin-x64",
            "linux-arm",
            "linux-arm64",
            "linux-x64",
            "win32-x86",
            "win32-x64",
          ]
      fail-fast: false

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/upload
        with:
          target: ${{ matrix.target }}

  win:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/upload
        with:
          target: win

  macos:
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/upload
        with:
          target: macos

  npm:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/upload
        with:
          target: npm

  # Not supported yet: https://github.com/oclif/oclif/issues/887
  #deb:
  #  runs-on: 'ubuntu-latest'
  #
  #  steps:
  #    - uses: actions/checkout@v3
  #      with:
  #        ref: ${{ github.event.pull_request.head.sha }}
  #    - uses: ./.github/actions/upload
  #      with:
  #        target: deb
